Fix 'set up' typo
ros2/launch pull request #813
Opened 2024-12-07 17:04 UTC by christophebedard

In this case, it should be "set up" and not just "setup"

2024-12-07 20:10 UTC, clalancette requested changes

2024-12-07 20:10 UTC, clalancette commented on launch/launch/launch_service.py
> +        :param: debug if True (not default), asyncio the logger are set up for debug
```suggestion
        :param: debug if True (not default), asyncio and the logger are set up for debug
```

2024-12-07 20:22 UTC, christophebedard commented on launch/launch/launch_service.py
> +        :param: debug if True (not default), asyncio the logger are set up for debug
good catch :laughing: fixed

2024-12-07 22:01 UTC, fujitatomoya approved these changes

2024-12-07 22:01 UTC, merged

2024-12-09 09:21 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy

2024-12-09 09:25 UTC, ahcorde commented
Pulls: ros2/launch#813
Gist: https://gist.githubusercontent.com/ahcorde/f00f288317936d9c6907a5379948edef/raw/094311b4e4807500bdb8c0917ab18411b59bf369/ros2.repos
BUILD args:  --packages-up-to launch --packages-above-and-dependencies launch
TEST args:  --packages-select launch --packages-above launch
ROS Distro: jazzy
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14922
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22234)](http://ci.ros2.org/job/ci_linux/22234/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16494)](http://ci.ros2.org/job/ci_linux-aarch64/16494/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1756)](http://ci.ros2.org/job/ci_linux-rhel/1756/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23000)](http://ci.ros2.org/job/ci_windows/23000/)